name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dependencies
      run: |
        sudo apt-get install cppcheck
        sudo apt-get install valgrind

    - name: cppcheck
      run: make cppcheck

    - name: unity
      run: make unity
    
    - name: sanitizer
      run: make sanitizer

    - name: gcov
      run: make gcov

    - name: valgrind
      run: make valgrind

